name: urbanledger
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  whatsapp_share:
    # git: https://gitlab.com/priyeshdabre/whatsapp_share.git
    path: packages/whatsapp_share
  app_settings: ^4.1.1
  camera: 0.9.3
  # card_scanner: ^1.0.1-prerelease
  card_scanner: 
    path: packages/card-scanner-flutter
  clipboard: ^0.1.3
  connectivity: ^3.0.3
  country_code_picker: ^2.0.1
  credit_card_validator: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dotted_border: ^2.0.0-nullsafety.0
  dotted_line: ^3.0.0
  emoji_picker_flutter: ^1.0.4
  equatable: ^2.0.3
  expandable: ^5.0.1
  file_picker: 3.0.1
  firebase_analytics: ^8.3.1
  firebase_core: ^1.2.1
  firebase_crashlytics: ^2.4.4
  firebase_messaging: ^11.2.0
  fl_chart: ^0.35.0
  flip_card: ^0.6.0
  flutter_bloc: ^7.1.0
  flutter_contact: ^0.9.1+8
  # flutter_contact: 
  #   git: https://gitlab.com/priyeshdabre/flutter_contact.git
  # flutter_downloader: ^1.6.0
  flutter_form_builder: ^6.0.0
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.1.4
  flutter_slidable: ^0.6.0
  flutter_svg: ^1.0.2
  flutter_web_browser: ^0.14.0
  fluttertoast: ^8.0.7
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  iban: ^1.0.0
  image_picker: ^0.8.4+4
  images_picker: ^1.2.1
  intl: ^0.17.0
  jiffy: ^4.1.0
  just_audio: ^0.7.4+1
  libphonenumber: ^2.0.0
  local_auth: ^1.1.5
  #local_auth:
    #path: ./local_auth/
  location: ^4.1.1
  math_expressions: ^2.1.0
  open_file: ^3.1.0
  path_provider: ^2.0.1
  pdf: ^3.4.2
  pdf_render: ^1.0.9
  permission_handler: ^6.1.3
  photo_view: ^0.12.0
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0
  record: ^2.1.0+1
  responsive_framework: ^0.1.0
  rflutter_alert: ^2.0.2
  shared_preferences: ^2.0.5
  socket_io_client: ^2.0.0-beta.3-nullsafety.0
  sqflite: ^2.0.0+3
  upgrader: ^3.3.0
  uuid: ^3.0.4
  vibration: ^1.7.4-nullsafety.0
  # audioplayers: ^0.19.0
  # assets_audio_player: 3.0.3+3
  share_plus: ^3.0.4
  tap_debouncer: ^2.0.0
  carousel_slider: ^4.0.0
#  charts_flutter: 0.11.0
  charts_flutter: ^0.12.0
  pie_chart: ^5.0.0
  firebase_dynamic_links: ^4.0.2
  # countup: ^0.1.3
  # readmore: ^1.0.2
  # flutter_screen: ^0.0.2
  # screen: ^0.0.5
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  animations: ^2.0.1
  url_launcher: ^6.0.10
  device_display_brightness: ^0.0.6
  pausable_timer: ^1.0.0+3
  timeago: ^3.1.0
  # qrscan: ^0.3.2
  phone_selector: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/kyc/
    - assets/images/Cashbook/
    - assets/fonts/
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/myprofile/
    - assets/icons/referafriend/
    - assets/icons/v2/


  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
    - family: Iceberg
      fonts:
        - asset: assets/fonts/Iceberg.ttf
    - family: Quivira
      fonts:
        - asset: assets/fonts/Quivira.otf
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Regular.ttf
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
